### ISSUE TITLE
2.04 - How to be a good corporate citizen when participating in an open source project.

### ISSUE THREAD

**Issue by pavithraes** [chanzuckerberg/czi-oss-training#30]
```[tasklist]
### Tasks
  - [ ] <https://github.com/Quansight-Labs/czi-oss-training/issues/40>
  - [ ] <https://github.com/Quansight-Labs/czi-oss-training/issues/37>
  - [ ] <https://github.com/Quansight-Labs/czi-oss-training/issues/36>
  - [ ] <https://github.com/Quansight-Labs/czi-oss-training/issues/17>
  - [ ] <https://github.com/Quansight-Labs/czi-oss-training/issues/42>
```
