### ISSUE TITLE
Discussion -  workshop slides requirements

### ISSUE THREAD

**Issue by trallard** [chanzuckerberg/czi-oss-training#7]
This should be done after the first draft review and following #3 #4 #5 

```[tasklist]
### Tasks
- [x] Format/medium (i.e. markdown-based, Google Slides)
- [x] Are there any branding requirements
- [x] Ensure whichever format agreed on can be accessed and modified by CZI, and is accessible to many readers/users
```
